### ISSUE TITLE
[ Feature Request ] Support searching for answers

### ISSUE THREAD

**Issue by nirberko** [veaos/veaos#7]
### Describe the solution you'd like
Now the searching engine is searching only for posts and not also for answers

When searching, we should show both relevant questions and answers.
I'm debating whether how we should show answers results, we can show them differently on the searching results page or we can show the question itself that the answer is associated with.

### Relevant files for this feature

[controllers/search.controller.ts](https://github.com/veaos/veaos/blob/main/packages/server/src/controllers/search.controller.ts)

**Comment by harshilparmar** [comment]
How about showing option besides search that user can search based on they want.

**Comment by nirberko** [comment]
> How about showing option besides search that user can search based on they want.

Makes sense. maybe by default, the searching will be both for questions and answers, and also besides the search box will be an option to search only by answers or questions

**Comment by nirberko** [comment]
im closing it because I forgot that the Post model is also for comments, so it does works for both questions and answers
